### ISSUE TITLE
Pytest extension hangs forever after initialization

### ISSUE THREAD

**Issue by frgfm** [CodSpeedHQ/action#113]
Hey there :wave: 

Thanks for the great work!
I recently tried to add Codspeed to a project of mine following the tutorial on the documentation. Unfortunately, even though I followed the tutorial, the job step times out.

Here is the PR https://github.com/frgfm/torch-cam/pull/270 and the failed job I just canceled to avoid eating all my CI minutes https://github.com/frgfm/torch-cam/actions/runs/10514500036/job/29132464450?pr=270

Mostly, the edits that I did:

GitHub workflow
```yaml
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -e ".[test]"
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest --codspeed tests/
```

and adding `@pytest.mark.benchmark` on a few tests that I run for coverage in another job.

Any hint on why this times out? :pray:
