### ISSUE TITLE
Different results running benchmarks with and without the action

### ISSUE THREAD

**Issue by andresliszt** [CodSpeedHQ/action#127]
Hello! Thanks for this amazing project. Maybe I'm too new on this, but I'm trying to configure the codspeed action, but I'm getting different results in some scenario. I'm working on a [project](https://github.com/andresliszt/pymoors) which mixes python and rust through [pyo3](https://github.com/PyO3/pyo3), and I have a test [here](https://github.com/andresliszt/pymoors/blob/main/tests/benchmarks/test_distance_matrix_benchmark.py), Which behaves completely different when I run it with and without the action. 

```python
import time

import pytest
import numpy as np
from scipy.spatial.distance import cdist  # type: ignore

from pymoors._pymoors import cross_euclidean_distances  # type: ignore


@pytest.mark.parametrize("n", [100, 500, 1000, 2000])
def test_compare_scipy_cdist_vs_pymoors(benchmark, n):
    matrix = np.random.rand(n, n)
    result_pymoors = benchmark(cross_euclidean_distances, matrix, matrix)
    # Measure the time for scipy's cdist using a timer
    start_time = time.perf_counter()
    result_scipy = cdist(matrix, matrix, metric="sqeuclidean")
    end_time = time.perf_counter()
    time_scipy = end_time - start_time
    # Check the result is the same
    np.testing.assert_allclose(result_pymoors, result_scipy, rtol=1e-5, atol=1e-8)
    # Check the time
    mean_time_pymoors = benchmark.stats.stats.mean
    assert mean_time_pymoors < time_scipy

```

If I use the action the tests run like if I've deployed my package in debug mode, comparable with the time i got locally when i run them in debug mode

```yaml
- name: Run benchmarks
  uses: CodSpeedHQ/action@v3
  with:
    token: ${{ secrets.CODSPEED_TOKEN }}
    run: |
      pytest -s -vvv tests/benchmarks --codspeed

```

But when I remove the action, and run the benchmark directly, the tests run just fine, like in release mode

```yaml
- name: Run benchmarks
  run: pytest -s -vvv tests/benchmarks --codspeed

```

Is the action introducing a change in the runner machine? Is there a doc where I can see what is the action doing?

Thanks!

**Comment by andresliszt** [comment]
I fixed it using 

```
- name: Run benchmarks
  uses: CodSpeedHQ/action@v3
  with:
    run: uv run pytest -s -vvv tests/benchmarks --codspeed
  env:
    CODSPEED_RUNNER_MODE: "walltime"
```
I can't find info related the `CODSPEED_RUNNER_MODE`, I found it looking at the runner code
