### ISSUE TITLE
option to upload *after* running tests in a different step?

### ISSUE THREAD

**Issue by tlambert03** [CodSpeedHQ/action#51]
in some cases, I would like to run my tests using a github action (e.g. to set up xvfb or something like that).  The fact that codspeed wants me to use its action to actually run tests makes that challenging.  Since it appears to just be uploading the results of having run `pytest --codspeed`, would it be possible to design this as an independent action?  Codecov, for example, does it like this:

```yaml
    - name: run tests
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
```

something like that seems like it would be be more flexible as it accommodates _any_ current testing action strategy

thanks!
